
USE FLIGHT_PROJECT;
SELECT SUM(PASSENGERS) AS
TOTAL_PASSENGERS
FROM FLIGHTS;
SELECT YEAR, SUM(PASSENGERS) AS
YEARLY_TOTAL
FROM FLIGHTS
GROUP BY YEAR
ORDER BY YEAR;

SELECT YEAR,SUM(PASSENGERS) AS TOTAL FROM FLIGHTS
GROUP BY year
ORDER BY TOTAL DESC
LIMIT 1;